apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: node-exporter
  name: node-exporter
  namespace: prometheus-system
spec:
  type: NodePort
  ports:
  - name: https
    port: 9100
    nodePort: 30910
  selector:
    name: node-exporter
