{
 "title": "Container Resources",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Node", "query": "node_load1" },
   { "name": "Limit", "query": "1, 3, 5, 10, 30, 50" }
  ]
 },
 "panels": [
  {
   "title": "average memory saturation",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{node =~ \"$Node\"} / on(namespaces, pod, container) group_left kube_pod_container_resource_limits_memory_bytes)"
    }
   ]
  },
  {
   "title": "Pods running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\", node =~ \"$Node\"})"
    }
   ]
  },
  {
   "title": "Unhealthy Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase !~ \"Running|Succeeded\", node=~\"$Node\"})"
    }
   ]
  },
  {
   "title": "average CPU saturation",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{node =~ \"$Node\", container !~ \"^(?:POD|)$\"}[5m]) / on(namespace, pod, container) group_left kube_pod_container_resource_limits_cpu_cores)"
    }
   ]
  },
  { "title": "Detailed", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "container CUP saturation - Top $Limit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk($Limit, rate(container_cpu_usage_seconds_total{node =~ \"$Node\", container !~ \"^(?:POD|)$\"}[5m]) / on(namespace, pod, container) group_left kube_pod_container_resource_limits_cpu_cores)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "container CPU utilization - Top $Limit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk($Limit, rate(container_cpu_usage_seconds_total{node =~ \"$Node\", container !~ \"|POD\"}[5m]))",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "container memory saturation - Top $Limit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk($Limit, container_memory_usage_bytes{node =~ \"$Node\"} / on(namespaces, pod, container) group_left kube_pod_container_resource_limits_memory_bytes)",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "container memory utilization - Top $Limit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk($Limit, container_memory_usage_bytes{node =~ \"$Node\", container !~ \"|POD\"})",
     "legendFormat": "{{ container }}"
    }
   ]
  }
 ]
}