{
 "title": "Node Resources",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Node", "query": "node_load1" }
  ]
 },
 "panels": [
  {
   "title": "node CPU saturation per core",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{node =~ \"$Node\", mode != \"idle\", mode != \"iowait\", mode !~ \"^(?:guest.*)$\"}[5m])) by (node, cpu)",
     "legendFormat": "{{ node }} - cpu - {{ cpu }}"
    }
   ]
  },
  {
   "title": "node cpu utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{node =~ \"$Node\", mode != \"idle\", mode != \"iowait\", mode !~ \"^(?:guest.*)$\"}[5m])) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "node CPU saturation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_load5{node =~ \"$Node\"} / on(node) group_left count(count(node_cpu_seconds_total) without (mode)) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Node memory saturation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - node_memory_MemAvailable_bytes{node =~ \"$Node\"} / ON(node) GROUP_LEFT node_memory_MemTotal_bytes",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "node disk saturation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - node_filesystem_avail_bytes{node =~ \"$Node\", mountpoint = \"/\"} / ON(node) GROUP_LEFT node_filesystem_size_bytes{mountpoint = \"/\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  }
 ]
}