apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kube-state-metrics
  name: kube-state-metrics
  namespace: monitoring-system
spec:
  type: NodePort
  ports:
  - name: http-metrics
    port: 8080
    nodePort: 30800
  - name: telemetry
    port: 8081
    nodePort: 30801
  selector:
    app.kubernetes.io/name: kube-state-metrics