apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring-system
  labels:
    app.kubernetes.io/name: prometheus
spec:
  type: NodePort
  ports:
  - name: https
    port: 9090
    nodePort: 30900
  selector:
    app.kubernetes.io/name: prometheus
